FROM python:3.12-slim

WORKDIR /app

# prevent python from creating .pyc files
ENV PYTHONDONTWRITEBYTECODE=1

# show python logs
ENV PYTHONUNBUFFERED=1

# INSTALL DEPENDENCIES
COPY requirements_api.txt .


RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir torch==2.5.1 \
      --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r requirements_api.txt



# copy application code
COPY api ./api
COPY src ./src
# copy label_encoder.pkl

COPY outputs ./outputs

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
