FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements_streamlit.txt .

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements_streamlit.txt

COPY frontend ./frontend

COPY outputs/nlp_classification_model/test_metrics.json ./outputs/nlp_classification_model/test_metrics.json

COPY outputs/nlp_classification_model/demo_df.csv ./outputs/nlp_classification_model/demo_df.csv
     
COPY outputs/nlp_classification_model/cm.csv ./outputs/nlp_classification_model/cm.csv     

EXPOSE 8501

CMD [ "streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
