name: Docker Build and Push

on:
  push:
    branches:
      - 10_CI_CD_Pipeline
    paths:
      - ".github/workflows/docker.yml"

env:
  AWS_REGION: ca-central-1
  API_REPOSITORY: financial-sentiment-api
  STREAMLIT_REPOSITORY: financial-sentiment-streamlit

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f Dockerfile.api \
            -t $ECR_REGISTRY/$API_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$API_REPOSITORY:latest \
            .

          docker push $ECR_REGISTRY/$API_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$API_REPOSITORY:latest

      - name: Build and push Streamlit image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f Dockerfile.streamlit \
            -t $ECR_REGISTRY/$STREAMLIT_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$STREAMLIT_REPOSITORY:latest \
            .

          docker push $ECR_REGISTRY/$STREAMLIT_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$STREAMLIT_REPOSITORY:latest